dist: trusty
language: php

php:
  - 7.4
  - 8.0

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env:
        - DEPS=latest
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 8.0
      env:
        - DEPS=latest
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - CS_CHECK=true
        - TEST_COVERAGE=true

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
